[frango_xadrez]
URL = "https://www.tudogostoso.com.br/receita/897-frango-xadrez.html"
frango = { quantity = 1, unit = "kg" }
azeite = { quantity = 60, unit = "mL"}
cebola = { quantity = 2, unit = "unid" }
alho = { quantity = 4, unit = "dentes" }
pimentao_verde = { quantity = 1, unit = "unid" }
pimentao_vermelho = { quantity = 1, unit = "unid" }
pimentao_amarelo = { quantity = 1, unit = "unid" }
shoyu = { quantity = 50, unit = "mL" }
amido_milho = { quantity = 2, unit = "colher_sopa" }

[frango_curry]
URL = "https://www.receiteria.com.br/receita/frango-ao-curry-com-leite-de-coco/"
frango = { quantity = 1, unit = "kg" }
oleo_canola = { quantity = 3, unit = "colher_sopa" }
curry_po = { quantity = 2, unit = "colher_sopa" }
cebola = { quantity = 1, unit = "unid" }
alho = { quantity = 2, unit = "dentes" }
leite_coco = { quantity = 200, unit = "mL" }
acucar = { quantity = 3.5, unit = "g" }
amido_milho = { quantity = 1.5, unit = "colher_sopa" }
pimentao_vermelho = { quantity = 1, unit = "unid" }

[frango_teriyaki]
URL = "https://www.tudogostoso.com.br/receita/66641-frango-teriaki.html"
frango = { quantity = 1, unit = "kg" }
gengibre_po = { quantity = 2, unit = "colher_cha" }
shoyu = { quantity = 45, unit = "mL" }
vinho_branco = { quantity = 30, unit = "mL" }
acucar = { quantity = 3.5, unit = "g" }
amido_milho = { quantity = 1, unit = "colher_sopa" }
azeite = { quantity = 50, unit = "mL"}
alho = { quantity = 1, unit = "dentes" }
gergelim = { quantity = 1, unit = "colher_sopa" }


[frango_molho_tomate]
URL = "https://www.tudoreceitas.com/receita-de-frango-ao-molho-de-tomate-11716.html"
frango = { quantity = 1, unit = "kg" }
alho = { quantity = 4, unit = "dentes" }
cebola = { quantity = 1, unit = "unid" }
tomate = { quantity = 2, unit = "unid" }
pimentao_vermelho = { quantity = 1, unit = "unid" }
molho_tomate = { quantity = 400, unit = "mL" }
azeite = { quantity = 60, unit = "mL"}
oregano = { quantity = 1, unit = "colher_sopa" }

[frango_grelhado_limao]
URL = "https://www.tudogostoso.com.br/receita/107124-file-de-frango-grelhado-com-limao.html"
frango = { quantity = 1, unit = "kg" }
limao = { quantity = 1, unit = "unid" }
manteiga = { quantity = 1, unit = "colher_sopa" }
pimenta_reino = { quantity = 1, unit = "colher_cha" }
mostarda = { quantity = 1, unit = "colher_sopa" }

[assado_panela]
URL = "https://www.tudogostoso.com.br/receita/66573-carne-assada-na-panela-de-pressao.html"
carne_para_assado = { quantity = 1, unit = "kg" }  
louro = { quantity = 2, unit = "folhas" }
vinagre_branco = { quantity = 2, unit = "colher_sopa" }
alho = { quantity = 4, unit = "dentes" }
paprica_picante = { quantity = 1, unit = "colher_cha" }
cebola = { quantity = 2, unit = "unid" }  
azeite = { quantity = 30, unit = "mL"}

[almondegas_bovinas]
URL = "https://www.tudogostoso.com.br/receita/80799-almondega-ao-molho-de-tomate-rapida-pratica-e-gostosa.html"
carne_moida = { quantity = 1, unit = "kg" }
ovo = { quantity = 4, unit = "unid" }
farinha_rosca = { quantity = 100, unit = "g" }
cebola = { quantity = 2, unit = "unid" }
alho = { quantity = 1, unit = "dentes" }
azeite = { quantity = 50, unit = "mL"}
molho_tomate = { quantity = 400, unit = "mL" }

[bife_molho_madeira]
URL = "https://www.tudogostoso.com.br/receita/17094-file-ao-molho-madeira-rapido-e-pratico.html"
carne_para_bife = { quantity = 1, unit = "kg" }  
alho = { quantity = 2, unit = "dentes" }
cebola = { quantity = 1, unit = "unid" }
manteiga = { quantity = 4, unit = "colher_sopa" }
caldo_carne = { quantity = 2, unit = "tablete" }
amido_milho = { quantity = 1, unit = "colher_sopa" }
vinho_tinto = { quantity = 100, unit = "mL" }
cogumelo_champignon = { quantity = 200, unit = "g" }
pimenta_reino = { quantity = 0.5, unit = "colher_cha" }





