[frango_xadrez]
frango = { quantity = 1, unit = "kg" }
vinagre_branco = { quantity = 1, unit = "colher_sopa" }
pimentao_verde = { quantity = 1, unit = "unid" }
pimentao_vermelho = { quantity = 1, unit = "unid" }
pimentao_amarelo = { quantity = 1, unit = "unid" }
cebola = { quantity = 1, unit = "unid" }
alho = { quantity = 4, unit = "dentes" }
gengibre_po = { quantity = 1, unit = "colher_cha" }
shoyu = { quantity = 100, unit = "mL" }
amido_milho = { quantity = 2, unit = "colher_sopa" }
amendoim_torrado = { quantity = 2, unit = "colher_sopa" }
azeite = { quantity = 50, unit = "mL"}

[frango_curry]
frango = { quantity = 1, unit = "kg" }
oleo_canola = { quantity = 3, unit = "colher_sopa" }
curry_po = { quantity = 2, unit = "colher_sopa" }
cebola = { quantity = 1, unit = "unid" }
alho = { quantity = 2, unit = "dentes" }
leite_coco = { quantity = 200, unit = "mL" }
molho_tomate = { quantity = 100, unit = "mL" }
acucar = { quantity = 12, unit = "g" }
amido_milho = { quantity = 1.5, unit = "colher_sopa" }
pimentao_vermelho = { quantity = 1, unit = "unid" }
limao = { quantity = 0.5, unit = "unid" }
creme_leite = { quantity = 120, unit = "mL" }
cebolinha = { quantity = 4, unit = "folhas" }
azeite = { quantity = 50, unit = "mL"}

[frango_teriyaki]
frango = { quantity = 1, unit = "kg" }
shoyu = { quantity = 120, unit = "mL" }
acucar = { quantity = 50, unit = "g" }
alho = { quantity = 3, unit = "dentes" }
gengibre_po = { quantity = 1, unit = "colher_cha" }
cebola = { quantity = 1, unit = "unid" }
cebolinha = { quantity = 3, unit = "folhas" }
amido_milho = { quantity = 1, unit = "colher_sopa" }
gergelim = { quantity = 1, unit = "colher_sopa" }
azeite = { quantity = 50, unit = "mL"}

[frango_molho_tomate]
URL = "https://www.tudoreceitas.com/receita-de-frango-ao-molho-de-tomate-11716.html"
frango = { quantity = 1, unit = "kg" }
alho = { quantity = 4, unit = "dentes" }
cebola = { quantity = 1, unit = "unid" }
tomate = { quantity = 2, unit = "unid" }
pimentao_vermelho = { quantity = 1, unit = "unid" }
molho_tomate = { quantity = 400, unit = "mL" }
azeite = { quantity = 60, unit = "mL"}
oregano = { quantity = 1, unit = "colher_sopa" }

[frango_grelhado_limao]
URL = "https://www.tudogostoso.com.br/receita/107124-file-de-frango-grelhado-com-limao.html"
frango = { quantity = 1, unit = "kg" }
limao = { quantity = 1, unit = "unid" }
manteiga = { quantity = 1, unit = "colher_sopa" }
pimenta_reino = { quantity = 1, unit = "colher_cha" }
mostarda = { quantity = 1, unit = "colher_sopa" }

[assado_de_panela]
carne_para_assado = { quantity = 1, unit = "kg" }  
cebola = { quantity = 2, unit = "unid" }  
alho = { quantity = 4, unit = "dentes" }
tomate = { quantity = 2, unit = "unid" }  
vinho_tinto = { quantity = 200, unit = "mL" }
louro = { quantity = 2, unit = "folhas" }
azeite = { quantity = 50, unit = "mL"}
paprica_picante = { quantity = 1, unit = "colher_cha" }

[almondegas_bovinas]
carne_moida = { quantity = 1, unit = "kg" }
cebola = { quantity = 3, unit = "unid" }
alho = { quantity = 6, unit = "dentes" }
farinha_rosca = { quantity = 100, unit = "g" }
leite = { quantity = 100, unit = "mL" }
ovo = { quantity = 2, unit = "unid" }
oregano = { quantity = 1, unit = "colher_sopa" }
queijo_parmesao = { quantity = 4, unit = "colher_sopa" }
molho_tomate = { quantity = 1000, unit = "mL" }
azeite = { quantity = 50, unit = "mL"}
manjericao = { quantity = 5, unit = "folhas" }

[bife_molho_madeira]
URL = "https://www.tudogostoso.com.br/receita/17094-file-ao-molho-madeira-rapido-e-pratico.html"
carne_para_bife = { quantity = 1, unit = "kg" }  
alho = { quantity = 2, unit = "dentes" }
cebola = { quantity = 1, unit = "unid" }
manteiga = { quantity = 4, unit = "colher_sopa" }
caldo_carne = { quantity = 2, unit = "tablete" }
amido_milho = { quantity = 1, unit = "colher_sopa" }
vinho = { quantity = 100, unit = "mL" }
cogumelo_champignon = { quantity = 200, unit = "g" }
pimenta_reino = { quantity = 0.5, unit = "colher_cha" }





